### ISSUE TITLE
After creating the first account, you cannot continue to create it later

### ISSUE THREAD

**Issue by zxl-qq927489674** [Crepe-Inc/CrepeSR#41]
fork main
mongodb 4.4.15
windows 10 
node  v16.15.1
`[14:09:07] ERROR<Database> E11000 duplicate key error collection: crepesr.accounts index: id_1 dup key: { id: null }
        ↳ MongoServerError: E11000 duplicate key error collection: crepesr.accounts index: id_1 dup key: { id: null }
    at D:\迅雷下载\铁道服务器端\CrepeSR-main\CrepeSR-main\node_modules\mongodb\src\operations\insert.ts:85:25
    at D:\迅雷下载\铁道服务器端\CrepeSR-main\CrepeSR-main\node_modules\mongodb\src\cmap\connection_pool.ts:489:13
    at D:\迅雷下载\铁道服务器端\CrepeSR-main\CrepeSR-main\node_modules\mongodb\src\sdam\server.ts:370:13
    at handleOperationResult (D:\迅雷下载\铁道服务器端\CrepeSR-main\CrepeSR-main\node_modules\mongodb\src\sdam\server.ts:541:14)
    at Connection.onMessage (D:\迅雷下载\铁道服务器端\CrepeSR-main\CrepeSR-main\node_modules\mongodb\src\cmap\connection.ts:462:5)
    at MessageStream.<anonymous> (D:\迅雷下载\铁道服务器端\CrepeSR-main\CrepeSR-main\node_modules\mongodb\src\cmap\connection.ts:268:56)
    at MessageStream.emit (node:events:527:28)
    at processIncomingData (D:\迅雷下载\铁道服务器端\CrepeSR-main\CrepeSR-main\node_modules\mongodb\src\cmap\message_stream.ts:194:14)
    at MessageStream._write (D:\迅雷下载\铁道服务器端\CrepeSR-main\CrepeSR-main\node_modules\mongodb\src\cmap\message_stream.ts:71:5)
    at writeOrBuffer (node:internal/streams/writable:389:12)
[14:09:07] </account> Account plays008 with UID 99606 created.`

**Comment by Chuchuwen9637** [comment]
将mongodb 升级到6.0解决问题了
